CREATE TABLESPACE mid_term Datafile 'mid_term.txt' size 50M
extent MANAGEMENT LOCAL AUTOALLOCATE;

Create user bmontoya IDENTIFIED by bmontoya DEFAULT TABLESPACE mid_term 
QUOTA UNLIMITED on mid_term;


CREATE ROLE MINI_DBA;

CREATE ROLE STUDENT;

GRANT CONNECT TO MINI_DBA;
GRANT CONNECT TO STUDENT;

GRANT CREATE TABLE TO MINI_DBA;

GRANT CREATE SEQUENCE TO MINI_DBA;

GRANT MINI_DBA TO bmontoya;