--------------------------------------------------------
-- Archivo creado  - viernes-octubre-12-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MUNICIPIO
--------------------------------------------------------

  CREATE TABLE "BMONTOYA"."MUNICIPIO" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
REM INSERTING into BMONTOYA.MUNICIPIO
SET DEFINE OFF;
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('10','LETICIA (CT)');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('11','ANDES');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('12','APARTADO');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('13','BARBOSA');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('14','BELLO');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('15','CAUCASIA');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('16','CIUDAD BOLIVAR');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('17','DON MATÃ?AS');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('18','ITUANGO');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('19','JARDIN');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('20','LA CEJA');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('21','MEDELLÃ?N (CT)');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('22','RIONEGRO');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('23','SALGAR');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('24','SANTAFE DE ANTIOQUIA');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('25','VALDIVIA');
Insert into BMONTOYA.MUNICIPIO (ID,NOMBRE) values ('26','ARAUCA (CT)');
--------------------------------------------------------
--  DDL for Index SYS_C006988
--------------------------------------------------------

  CREATE UNIQUE INDEX "BMONTOYA"."SYS_C006988" ON "BMONTOYA"."MUNICIPIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  Constraints for Table MUNICIPIO
--------------------------------------------------------

  ALTER TABLE "BMONTOYA"."MUNICIPIO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM"  ENABLE;
  ALTER TABLE "BMONTOYA"."MUNICIPIO" MODIFY ("ID" NOT NULL ENABLE);
